exclude = [
    ".venv",
    "build",
    ".venv3.8",
    ".venv312",
    ".git",
]
select = [
    "ALL"
]
ignore = [
    "C901", "N818", "N805", "D1", "D2", "D400", "D415", "D401", "YTT", "ANN", "S", "B", "C4", "DTZ", "EM", "EXE",
    "FA", "INP", "PYI024", "PT", "RET503", "RET505", "ARG", "PTH123", "TD", "FIX", "PL", "RUF013", "TRY003", "TRY200"
]

line-length = 120
[flake8-quotes]
inline-quotes = "single"

[per-file-ignores]
"pantherdb/__init__.py" = ["F405"]
"pantherdb/pantherdb.py" = ["A003"]
